-- MixPilot cloud observability schema
-- Source-controlled on GitHub; deployed to a dedicated Supabase Postgres project.

create extension if not exists pgcrypto;

create schema if not exists mixpilot_private;

create table if not exists public.mixpilot_devices (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null references auth.users(id) on delete cascade,
    installation_id uuid not null,
    device_name text,
    platform text not null default 'macOS',
    app_version text,
    rekordbox_version text,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (owner_id, installation_id)
);

create table if not exists public.mixpilot_sessions (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null references auth.users(id) on delete cascade,
    device_id uuid not null references public.mixpilot_devices(id) on delete cascade,
    started_at timestamptz not null default now(),
    ended_at timestamptz,
    app_version text,
    dj_backend text,
    rekordbox_version text,
    live_mode boolean not null default false,
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.mixpilot_events (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    device_id uuid not null references public.mixpilot_devices(id) on delete cascade,
    session_id uuid references public.mixpilot_sessions(id) on delete set null,
    occurred_at timestamptz not null default now(),
    category text not null,
    name text not null,
    severity text not null default 'info' check (severity in ('debug','info','warning','error','critical')),
    payload jsonb not null default '{}'::jsonb,
    client_event_id uuid not null,
    unique (owner_id, client_event_id)
);

create table if not exists public.rekordbox_validation_reports (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null references auth.users(id) on delete cascade,
    device_id uuid not null references public.mixpilot_devices(id) on delete cascade,
    rekordbox_version text not null,
    controller_name text not null,
    preset_signature text not null,
    critical_ready boolean not null default false,
    completion_ratio double precision not null default 0 check (completion_ratio between 0 and 1),
    passed_ratio double precision not null default 0 check (passed_ratio between 0 and 1),
    report jsonb not null,
    validated_at timestamptz not null default now(),
    unique (owner_id, device_id, rekordbox_version, preset_signature)
);

create table if not exists public.mixpilot_commands (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid not null references auth.users(id) on delete cascade,
    device_id uuid not null references public.mixpilot_devices(id) on delete cascade,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    command text not null,
    payload jsonb not null default '{}'::jsonb,
    status text not null default 'pending' check (status in ('pending','accepted','completed','failed','expired')),
    completed_at timestamptz,
    result jsonb
);

create index if not exists mixpilot_devices_owner_last_seen_idx
    on public.mixpilot_devices (owner_id, last_seen_at desc);
create index if not exists mixpilot_sessions_owner_started_idx
    on public.mixpilot_sessions (owner_id, started_at desc);
create index if not exists mixpilot_events_owner_time_idx
    on public.mixpilot_events (owner_id, occurred_at desc);
create index if not exists mixpilot_events_session_time_idx
    on public.mixpilot_events (session_id, occurred_at desc);
create index if not exists mixpilot_events_category_name_idx
    on public.mixpilot_events (category, name, occurred_at desc);
create index if not exists mixpilot_commands_device_status_idx
    on public.mixpilot_commands (device_id, status, created_at);

alter table public.mixpilot_devices enable row level security;
alter table public.mixpilot_sessions enable row level security;
alter table public.mixpilot_events enable row level security;
alter table public.rekordbox_validation_reports enable row level security;
alter table public.mixpilot_commands enable row level security;

revoke all on public.mixpilot_devices from anon;
revoke all on public.mixpilot_sessions from anon;
revoke all on public.mixpilot_events from anon;
revoke all on public.rekordbox_validation_reports from anon;
revoke all on public.mixpilot_commands from anon;

grant select, insert, update on public.mixpilot_devices to authenticated;
grant select, insert, update on public.mixpilot_sessions to authenticated;
grant select, insert on public.mixpilot_events to authenticated;
grant select, insert, update on public.rekordbox_validation_reports to authenticated;
grant select, update on public.mixpilot_commands to authenticated;
grant usage, select on sequence public.mixpilot_events_id_seq to authenticated;

create policy "owners read devices"
on public.mixpilot_devices for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "owners insert devices"
on public.mixpilot_devices for insert
to authenticated
with check ((select auth.uid()) = owner_id);

create policy "owners update devices"
on public.mixpilot_devices for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "owners read sessions"
on public.mixpilot_sessions for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "owners insert sessions"
on public.mixpilot_sessions for insert
to authenticated
with check ((select auth.uid()) = owner_id);

create policy "owners update sessions"
on public.mixpilot_sessions for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "owners read events"
on public.mixpilot_events for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "owners insert events"
on public.mixpilot_events for insert
to authenticated
with check ((select auth.uid()) = owner_id);

create policy "owners read validation reports"
on public.rekordbox_validation_reports for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "owners insert validation reports"
on public.rekordbox_validation_reports for insert
to authenticated
with check ((select auth.uid()) = owner_id);

create policy "owners update validation reports"
on public.rekordbox_validation_reports for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "owners read commands"
on public.mixpilot_commands for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy "owners update commands"
on public.mixpilot_commands for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

-- Commands are deliberately not insertable from the desktop client.
-- An authenticated admin/dashboard or a JWT-protected Edge Function can enqueue
-- allowlisted commands after checking ownership and expiry.

create or replace view public.mixpilot_device_health
with (security_invoker = true)
as
select
    d.owner_id,
    d.id as device_id,
    d.device_name,
    d.app_version,
    d.rekordbox_version,
    d.last_seen_at,
    (now() - d.last_seen_at) < interval '2 minutes' as online,
    count(e.id) filter (where e.severity in ('error','critical') and e.occurred_at > now() - interval '24 hours') as errors_last_24h,
    max(e.occurred_at) as last_event_at
from public.mixpilot_devices d
left join public.mixpilot_events e on e.device_id = d.id
group by d.owner_id, d.id;

grant select on public.mixpilot_device_health to authenticated;
