-- Harden maintenance commands, publication metadata, telemetry aggregation and retention.
-- Apple Developer ID and notarization are deliberately not required here.

alter table public.mixpilot_commands
    add column if not exists idempotency_key uuid not null default gen_random_uuid(),
    add column if not exists sequence_number bigint generated by default as identity,
    add column if not exists claimed_at timestamptz,
    add column if not exists claimed_by_instance text,
    add column if not exists attempt_count integer not null default 0,
    add column if not exists failure_code text;

alter table public.mixpilot_commands
    add constraint mixpilot_commands_device_idempotency_key
        unique (device_id, idempotency_key),
    add constraint mixpilot_commands_claim_fields_check
        check (
            (claimed_at is null and claimed_by_instance is null)
            or (claimed_at is not null and length(claimed_by_instance) between 8 and 160)
        ),
    add constraint mixpilot_commands_attempt_count_check
        check (attempt_count between 0 and 20),
    add constraint mixpilot_commands_expiry_window_check
        check (expires_at > created_at and expires_at <= created_at + interval '1 day'),
    add constraint mixpilot_commands_payload_size_check
        check (octet_length(payload::text) <= 16384),
    add constraint mixpilot_commands_result_size_check
        check (result is null or octet_length(result::text) <= 16384);

create index if not exists mixpilot_commands_claimable_idx
    on public.mixpilot_commands (device_id, status, sequence_number)
    where claimed_at is null;

create or replace function public.claim_mixpilot_commands(
    p_device_id uuid,
    p_instance_id text,
    p_limit integer default 10
)
returns setof public.mixpilot_commands
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
    if auth.uid() is null then
        raise exception 'Authentication required' using errcode = '42501';
    end if;
    if p_instance_id is null or length(p_instance_id) not between 8 and 160 then
        raise exception 'Invalid instance identifier' using errcode = '22023';
    end if;

    return query
    with candidates as (
        select c.id
        from public.mixpilot_commands c
        where c.owner_id = auth.uid()
          and c.device_id = p_device_id
          and c.status = 'pending'
          and c.claimed_at is null
          and c.expires_at > now()
        order by c.sequence_number
        for update skip locked
        limit least(greatest(coalesce(p_limit, 1), 1), 10)
    )
    update public.mixpilot_commands c
       set status = 'accepted',
           claimed_at = now(),
           claimed_by_instance = p_instance_id,
           attempt_count = c.attempt_count + 1
      from candidates
     where c.id = candidates.id
    returning c.*;
end;
$$;

revoke all on function public.claim_mixpilot_commands(uuid, text, integer)
    from public, anon;
grant execute on function public.claim_mixpilot_commands(uuid, text, integer)
    to authenticated, service_role;

create or replace function public.complete_mixpilot_command(
    p_command_id uuid,
    p_instance_id text,
    p_succeeded boolean,
    p_result jsonb default '{}'::jsonb,
    p_failure_code text default null
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    updated_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required' using errcode = '42501';
    end if;
    if p_instance_id is null or length(p_instance_id) not between 8 and 160 then
        raise exception 'Invalid instance identifier' using errcode = '22023';
    end if;
    if octet_length(coalesce(p_result, '{}'::jsonb)::text) > 16384 then
        raise exception 'Command result is too large' using errcode = '22023';
    end if;

    update public.mixpilot_commands
       set status = case when p_succeeded then 'completed' else 'failed' end,
           completed_at = now(),
           result = coalesce(p_result, '{}'::jsonb),
           failure_code = case when p_succeeded then null else left(p_failure_code, 120) end
     where id = p_command_id
       and owner_id = auth.uid()
       and status = 'accepted'
       and claimed_by_instance = p_instance_id
       and completed_at is null;

    get diagnostics updated_count = row_count;
    return updated_count = 1;
end;
$$;

revoke all on function public.complete_mixpilot_command(uuid, text, boolean, jsonb, text)
    from public, anon;
grant execute on function public.complete_mixpilot_command(uuid, text, boolean, jsonb, text)
    to authenticated, service_role;

-- Strict validation for values received through the public REST API.
alter table public.mixpilot_events
    add constraint mixpilot_events_category_length_check
        check (length(category) between 1 and 80),
    add constraint mixpilot_events_name_length_check
        check (length(name) between 1 and 80),
    add constraint mixpilot_events_payload_size_check
        check (octet_length(payload::text) <= 8192),
    add constraint mixpilot_events_timestamp_window_check
        check (occurred_at <= now() + interval '5 minutes');

alter table public.mixpilot_mapping_releases
    add constraint mixpilot_mapping_profile_size_check
        check (octet_length(profile::text) <= 262144),
    add constraint mixpilot_mapping_validation_size_check
        check (octet_length(validation_summary::text) <= 65536);

alter table public.mixpilot_releases
    add constraint mixpilot_releases_notes_size_check
        check (octet_length(release_notes) <= 32768);

create or replace function mixpilot_private.is_allowed_distribution_url(value text)
returns boolean
language sql
immutable
strict
set search_path = pg_catalog
as $$
    select value ~ '^https://github[.]com/lucasmezen972-ui/Mixpilot/releases(/|$)'
        or value ~ '^https://objects[.]githubusercontent[.]com/'
        or value ~ '^https://cqppkklfugbixpxwitab[.]supabase[.]co/storage/v1/object/public/mixpilot-(releases|mappings)/';
$$;

revoke all on function mixpilot_private.is_allowed_distribution_url(text)
    from public, anon, authenticated;

create or replace function public.mixpilot_guard_release_publication()
returns trigger
language plpgsql
set search_path = pg_catalog, public, mixpilot_private
as $$
begin
    if new.status = 'published' then
        if new.published_at is null or new.rollout_percentage <= 0 then
            raise exception 'Published releases require published_at and rollout_percentage > 0';
        end if;
        if new.signature is null or length(new.signature) < 32 then
            raise exception 'Published releases require an independent publisher signature';
        end if;
        if not mixpilot_private.is_allowed_distribution_url(new.download_url) then
            raise exception 'Release download URL is not on the MixPilot allowlist';
        end if;
        if new.release_page_url is not null
           and not mixpilot_private.is_allowed_distribution_url(new.release_page_url) then
            raise exception 'Release page URL is not on the MixPilot allowlist';
        end if;
    end if;
    return new;
end;
$$;

revoke all on function public.mixpilot_guard_release_publication()
    from public, anon, authenticated;

drop trigger if exists mixpilot_guard_release_publication
    on public.mixpilot_releases;
create trigger mixpilot_guard_release_publication
before insert or update on public.mixpilot_releases
for each row execute function public.mixpilot_guard_release_publication();

create or replace function public.mixpilot_guard_mapping_publication()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
    if new.status = 'published' then
        if new.published_at is null or new.rollout_percentage <= 0 then
            raise exception 'Published mappings require published_at and rollout_percentage > 0';
        end if;
        if new.publisher_signature is null or length(new.publisher_signature) < 32 then
            raise exception 'Published mappings require an independent publisher signature';
        end if;
        if new.source_repository is distinct from 'lucasmezen972-ui/Mixpilot'
           or new.source_commit_sha is null
           or new.source_manifest_path is null
           or new.source_manifest_sha256 is null then
            raise exception 'Published mappings require trusted immutable GitHub provenance';
        end if;
        if new.generated_preset_sha256 is null then
            raise exception 'Published mappings require the generated preset digest';
        end if;
        if coalesce(new.validation_summary->>'unit_tests', '') <> 'passed'
           or coalesce(new.validation_summary->>'release_build', '') <> 'passed'
           or coalesce(new.validation_summary->>'dmg_checksum', '') <> 'passed' then
            raise exception 'Published mappings require completed CI validation';
        end if;
        if new.channel = 'stable'
           and coalesce(new.validation_summary->>'device_validation', '') <> 'passed' then
            raise exception 'Stable mappings require real device validation';
        end if;
    end if;
    return new;
end;
$$;

revoke all on function public.mixpilot_guard_mapping_publication()
    from public, anon, authenticated;
grant execute on function public.mixpilot_guard_mapping_publication()
    to service_role;

-- Client telemetry never becomes a global incident unless an administrator has
-- explicitly allowlisted the exact category/name pair.
create table if not exists mixpilot_private.incident_event_allowlist (
    category text not null,
    name text not null,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    primary key (category, name)
);

revoke all on mixpilot_private.incident_event_allowlist
    from public, anon, authenticated;

create or replace function mixpilot_private.aggregate_event_incident()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, mixpilot_private
as $$
declare
    incident_fingerprint text;
begin
    if new.severity not in ('error', 'critical') then
        return new;
    end if;
    if not exists (
        select 1
        from mixpilot_private.incident_event_allowlist a
        where a.category = new.category
          and a.name = new.name
          and a.enabled
    ) then
        return new;
    end if;

    incident_fingerprint := encode(
        extensions.digest(convert_to(new.category || ':' || new.name, 'UTF8'), 'sha256'),
        'hex'
    );

    insert into public.mixpilot_incidents (
        fingerprint, category, name, severity, status, occurrences,
        affected_devices, first_seen_at, last_seen_at, safe_summary
    ) values (
        incident_fingerprint, left(new.category, 80), left(new.name, 80),
        new.severity, 'open', 1, 1, new.occurred_at, new.occurred_at,
        left(new.category || ' / ' || new.name, 180)
    )
    on conflict (fingerprint) do update
    set occurrences = public.mixpilot_incidents.occurrences + 1,
        severity = case
            when excluded.severity = 'critical' then 'critical'
            else public.mixpilot_incidents.severity
        end,
        last_seen_at = greatest(public.mixpilot_incidents.last_seen_at, excluded.last_seen_at),
        updated_at = now();

    return new;
end;
$$;

revoke all on function mixpilot_private.aggregate_event_incident()
    from public, anon, authenticated;

create or replace function mixpilot_private.purge_expired_data(p_batch_size integer default 5000)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    event_count integer := 0;
    command_count integer := 0;
begin
    with expired as (
        select id from public.mixpilot_events
        where expires_at <= now()
        order by expires_at
        limit least(greatest(coalesce(p_batch_size, 5000), 1), 20000)
    )
    delete from public.mixpilot_events e
    using expired x
    where e.id = x.id;
    get diagnostics event_count = row_count;

    with expired as (
        select id from public.mixpilot_commands
        where expires_at <= now()
          and (completed_at is null or completed_at < now() - interval '7 days')
        order by expires_at
        limit least(greatest(coalesce(p_batch_size, 5000), 1), 20000)
    )
    delete from public.mixpilot_commands c
    using expired x
    where c.id = x.id;
    get diagnostics command_count = row_count;

    return jsonb_build_object(
        'events_deleted', event_count,
        'commands_deleted', command_count
    );
end;
$$;

revoke all on function mixpilot_private.purge_expired_data(integer)
    from public, anon, authenticated;
grant execute on function mixpilot_private.purge_expired_data(integer)
    to service_role;

create extension if not exists pg_cron with schema extensions;

do $$
declare
    existing_job bigint;
begin
    for existing_job in
        select jobid from cron.job where jobname = 'mixpilot-purge-expired-data'
    loop
        perform cron.unschedule(existing_job);
    end loop;

    perform cron.schedule(
        'mixpilot-purge-expired-data',
        '17 4 * * *',
        $cron$select mixpilot_private.purge_expired_data(5000);$cron$
    );
end
$$;
